# .github/workflows/second-workflow.yml

name: Second Workflow
on: [push]
jobs:
  second-job:
    runs-on: ubuntu-latest
    needs: first-workflow.first-job
    steps:
      - run: echo "This is the second job"
