name: Synth
on: [push]
permissions:
  id-token: write
  contents: read
  
  
jobs:
  DeployStacks:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependiencies
        run: yarn

      - name: Synth stack
        run: yarn cdk syh
